name: Docker Workflow
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install pylint
      run: |
        pip install pylint
    - name: Create pylintrc file
      run: |
        pylint --generate-rcfile > .pylintrc
    - name: Linter test
      run: |
        pylint --disable=all $(git ls-file '*.py')
    - name: Run a Docker
      run: docker build -t complete_app .
